"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var EntityType;
(function (EntityType) {
    EntityType["User"] = "USER";
    EntityType["Ride"] = "RIDE";
    EntityType["Group"] = "GROUP";
    EntityType["Event"] = "EVENT";
    EntityType["Photo"] = "PHOTO";
    EntityType["PhotoAlbum"] = "PHOTO_ALBUM";
    EntityType["Status"] = "STATUS";
    EntityType["Conversation"] = "CONVERSATION";
    EntityType["TextWallMessage"] = "TEXT_WALL_MESSAGE";
    EntityType["Story"] = "STORY";
    EntityType["Location"] = "LOCATION";
    EntityType["Comment"] = "COMMENT";
    EntityType["Like"] = "LIKE";
    EntityType["UrlTag"] = "URL_TAG";
    EntityType["HashTag"] = "HASH_TAG";
    EntityType["UserMentionTag"] = "USER_MENTION_TAG";
    EntityType["ConversationMessage"] = "CONVERSATION_MESSAGE";
})(EntityType = exports.EntityType || (exports.EntityType = {}));
