export enum EntityType {
    User = 'USER',
    Ride = 'RIDE',
    Group = 'GROUP',
    Event = 'EVENT',
    Photo = 'PHOTO',
    PhotoAlbum = 'PHOTO_ALBUM',
    Status = 'STATUS',
    Conversation = 'CONVERSATION',
    TextWallMessage = 'TEXT_WALL_MESSAGE',
    Story = 'STORY',
    Location = 'LOCATION',
    Comment = 'COMMENT',
    Like = 'LIKE',
    UrlTag = 'URL_TAG',
    HashTag = 'HASH_TAG',
    UserMentionTag = 'USER_MENTION_TAG',
    ConversationMessage = 'CONVERSATION_MESSAGE',
}